### ISSUE TITLE
sketch visual style (portrait)

### ISSUE THREAD

**Issue by mrzl** [Schwittleymani/ECO#189]

**Comment by transfluxus** [comment]
Possibilites:
- Slack webinterface +  style adaption
- IRC webinterface + style adaption

**Comment by transfluxus** [comment]
run snippet in chrome. and close developer tools. height adjusts after 2secs
```
// clean slack browser snippet
ciao = []
ciao.push($('.client_channels_list_container'))
ciao.push($('#client_header'))
ciao.push($('#footer'))

for(el of ciao){
    el.css('display','none')
}

$('#messages_container').css('height', '100%')

setTimeout(function(){
$('#msgs_scroller_div').css('height', '100%')    
},2000)
```

**Comment by mrzl** [comment]
i was rather thinking of something in this direction with relative sizes of fonts and message blobs, so we can use any resolution and it just adjusts.

![44250027-vector-flat-phone-chat-bubbles-sms-messages-speech-bubbles-short-message-service-bubbles--stock-vector](https://cloud.githubusercontent.com/assets/1453951/25072160/3ad82256-22c8-11e7-9862-0eb7ed8f8e5c.jpg)

adding your picture of the message tree as a reference:

<img width="1057" alt="screen shot 2017-04-15 at 14 04 54" src="https://cloud.githubusercontent.com/assets/1453951/25072174/89ec12ee-22c8-11e7-9c98-3c5e07c6246b.png">

**Comment by transfluxus** [comment]
Mmh. Ja But this is a me and others perspective.  So who would be who

**Comment by schwittlick** [comment]
https://paper.dropbox.com/doc/ECO-v4.0-dirty-57A60gxwxruZbNeBdXOJ3
