### ISSUE TITLE
implement author metadata in w2v model

### ISSUE THREAD

**Issue by mrzl** [Schwittleymani/ECO#190]

**Comment by mrzl** [comment]
in order to have author metadata:

    1. in parser, create a csv for each parsed file, with sentence and filename in each line
    2. concat everything in one file ala parsed_v3_valid_with_authors.txt
    3. in https://github.com/Schwittleymani/ECO/blob/master/src/python/modelbuilder/doc2vec_builder.py#L13 split the line and use the author as a second label (tags accepts a list of labels)
    4. implement get_author_tag(sentence) (which is sentence.tags[1], sentence.tags[0] is the unique id)

**Comment by mrzl** [comment]
parsing everything new, exporting to csv files: /home/marcel/drive/data/eco/NAIL_DATAFIELD_txt/parsed_v4

**Comment by mrzl** [comment]
trained new doc2vec model: 

    /mnt/drive1/data/eco/NAIL_DATAFIELD_txt/parsed_v4/parsed_v4_valid.doc2vec
    /mnt/drive1/data/eco/NAIL_DATAFIELD_txt/parsed_v4/parsed_v4_valid.doc2vec.docvecs.doctag_syn0.npy

**Comment by schwittlick** [comment]
trained again: /mnt/drive1/data/eco/NAIL_DATAFIELD_txt/parsed_v4/parsed_v4_valid_tagged.doc2vec
